###################################################
# SERVER
###################################################

server.port=8082

###################################################
# DATABASE
###################################################

spring.datasource.url=jdbc:postgresql://localhost:5433/enterprise-ai-agent
spring.datasource.username=postgres
spring.datasource.password=postgres

###################################################
# JPA
###################################################

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

###################################################
# OLLAMA
###################################################

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.options.temperature=0.7

###################################################
# STORAGE
###################################################

app.storage.location=uploads

###################################################
# PGVECTOR
###################################################

spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance

###################################################
# WEATHER
###################################################

weather.api.key=8d66b153ec1ef1caffcf190e5f0d7bc0
weather.api.url=https://api.openweathermap.org/data/2.5/weather

###################################################
# MAIL
###################################################

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

###################################################
# SWAGGER
###################################################

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

###################################################
# JWT
###################################################

jwt.secret=ThisIsMySuperSecretKeyForEnterpriseAIAgentProject123456789
jwt.expiration=86400000

###################################################
# LOGGING
###################################################

logging.level.root=INFO
logging.level.com.aiagent.enterprise_ai_agent=INFO
logging.file.name=logs/enterprise-ai-agent.log

###################################################
# ACTUATOR
###################################################

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

###################################################
# INFO
###################################################

info.app.name=Enterprise AI Agent
info.app.description=Production Ready Enterprise AI Agent
info.app.version=1.0.0
info.app.author=Shubham Kumawat