spring.application.name=enterprise-ai-agent

server.port=8082

#spring.datasource.url=jdbc:postgresql://localhost:5433/enterprise-ai-agent
spring.datasource.url=jdbc:postgresql://host.docker.internal:5433/enterprise-ai-agent
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always


#ollama
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=qwen2.5:7b
#spring.ai.ollama.chat.options.temperature=0.2

#spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.base-url=http://host.docker.internal:11434
spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.options.temperature=0.7

app.storage.location=uploads
#vectorstore
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
# OpenAI
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4.1-mini

weather.api.key=8d66b153ec1ef1caffcf190e5f0d7bc0

weather.api.url=https://api.openweathermap.org/data/2.5/weather

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.secret=ThisIsMySuperSecretKeyForEnterpriseAIAgentProject123456789

jwt.expiration=86400000




#############################
# Logging
#############################

logging.level.root=INFO

logging.level.com.aiagent.enterprise_ai_agent=DEBUG

logging.level.org.springframework.web=INFO

logging.level.org.springframework.security=WARN

logging.level.org.hibernate.SQL=OFF

logging.level.org.hibernate.type.descriptor.sql=OFF

logging.file.name=logs/enterprise-ai-agent.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n


###################################################
# ACTUATOR
###################################################

management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings

management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=Enterprise AI Agent

info.app.description=Production Ready Enterprise AI Agent

info.app.version=1.0.0

info.app.author=Shubham Kumawat