package com.aiagent.enterprise_ai_agent.service;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

import com.aiagent.enterprise_ai_agent.config.PromptConfig;
import com.aiagent.enterprise_ai_agent.entity.Conversation;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class TitleService {

    private final ChatClient chatClient;
    private final ConversationService conversationService;

    /**
     * Generate title only once.
     */
    public void generateTitle(
            Conversation conversation,
            String firstMessage) {

        // Already has title
        if (conversation.getTitle() != null &&
            !conversation.getTitle().isBlank()) {
            return;
        }

        String title = chatClient
                .prompt()
                .user(PromptConfig.TITLE_PROMPT.formatted(firstMessage))
                .call()
                .content();

        if (title == null || title.isBlank()) {
            title = "New Chat";
        }

        conversation.setTitle(cleanTitle(title));

        conversationService.save(conversation);
    }

    /**
     * Remove unwanted characters generated by LLM.
     */
    private String cleanTitle(String title) {

        title = title.replace("\"", "");
        title = title.replace("\n", "");
        title = title.trim();

        if (title.length() > 100) {
            title = title.substring(0, 100);
        }

        return title;
    }
    public String generateTitle(String firstMessage) {

        return chatClient
                .prompt()
                .user(PromptConfig.TITLE_PROMPT.formatted(firstMessage))
                .call()
                .content()
                .trim();
    }

}